### ISSUE TITLE
cannot build the code

### ISSUE THREAD

**Issue by a-stevan** [DeadlockCode/n-body#1]
hello there :wave:

i wanted to give the simulations from [_Making an N-Body Simulation_](https://www.youtube.com/watch?v=L9N7ZbGSckk) a try, but i could not compile the code :cry: 

hoping there is a solution for this :pray: 
cheers!

## repro
- run either one of the following commands
```bash
cargo check
```
```bash
cargo build
```
```bash
cargo run --release
```
- get the following error
```
error[E0432]: unresolved import `winit::platform::windows`
  --> /home/disc/a.stevan/.local/share/cargo/git/checkouts/quarkstrom-59b32b829dff6ef4/db52869/src/lib.rs:17:15
   |
17 |     platform::windows::EventLoopBuilderExtWindows,
   |               ^^^^^^^ could not find `windows` in `platform`

error[E0599]: no method named `with_any_thread` found for struct `EventLoopBuilder` in the current scope
   --> /home/disc/a.stevan/.local/share/cargo/git/checkouts/quarkstrom-59b32b829dff6ef4/db52869/src/lib.rs:510:50
    |
510 |         let event_loop = EventLoopBuilder::new().with_any_thread(true).build();
    |                                                  ^^^^^^^^^^^^^^^ method not found in `EventLoopBuilder<()>`
    |
    = help: items from traits can only be used if the trait is in scope
help: the following traits are implemented but not in scope; perhaps add a `use` for one of them:
    |
1   + use winit::platform::wayland::EventLoopBuilderExtWayland;
    |
1   + use winit::platform::x11::EventLoopBuilderExtX11;
    |
```

**Comment by a-stevan** [comment]
so what i did is the following:
- i forked the two repos: [a-stevan/quarkstrom](https://github.com/a-stevan/quarkstrom) and [a-stevan/n-body](https://github.com/a-stevan/n-body) 
- i fixed OS-based imports in `quarkstrom` in the [`a-stevan:quarktrom:fix` branch](https://github.com/DeadlockCode/quarkstrom/compare/master...a-stevan:quarkstrom:fix) 
- i'm using this new dependency and fixed a call to `ctx.draw_circle` in the [`a-stevan:n-body:fix` branch](https://github.com/DeadlockCode/n-body/compare/main...a-stevan:n-body:fix)

hope that helps people play with these simulations :relieved:

**Comment by krakow10** [comment]
Check it out, by moving the simulation onto a separate thread and putting the event loop onto the main thread, the platform-specific code can be dropped entirely:

https://github.com/DeadlockCode/quarkstrom/pull/1/commits/7f1d647aa2ce1a0756e9d0b1f43f2bfa6a8e0778

You could update the quarkstrom version, apply the same fix to the main function here, and open a pull request.

**Comment by a-stevan** [comment]
ooooh, interesting, thanks @krakow10 :pray:

**Comment by DeadlockCode** [comment]
The root cause has been solved and the necessary changes have been applied here 7ddee5d which closes this issue.

**Comment by a-stevan** [comment]
thanks for the fix :pray:
